name: Mannys Implementation of a Custom Action
description: This action greets persons
inputs:
  person:
    description: 'The person to greet'
    required: true
    default: 'Monalisa Octocat'
runs:
  using: node16
  main: src/index.js